import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/app/components/Nav.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sundown Boulevard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav></Nav>

        {children}
      </body>
    </html>
  );
}
